version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"

  content-service:
    image: content-service
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  user-service:
    image: user-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
